import React from 'react'
import { Faqtopbox } from '../F&Q/faqtopbox'
import { MobileSubcribe } from '../Component/share/mobileSubcribe'
import { MainContent } from './mainContent'

export const metadata = {
  title: 'Terms & condition',
  description: 'Generated by create next app',
}

const Terms = () => {
  return (
    <>
   <Faqtopbox title="Local Tasker UK" subtitle="Terms of Service" para="These Terms of Service constitute a legally binding
agreement between you and Local Tasker UK LTD." img1="/termsofservices.png" img2="/termsofservicesbigcircle.png" img="/termsofservicesbigcircle.png"/> 
    <MainContent/>
    <MobileSubcribe/>
    </> 
  )
}

export default Terms