import React from 'react'
import { Faqtopbox } from './faqtopbox'
import { Faqbox } from './faqbox';
import { Subcribe } from '../Component/share/Subcribe';
import { MobileSubcribe } from '../Component/share/mobileSubcribe';

export const metadata = {
  title: 'F&Q',
  description: 'Generated by create next app',
}

const FAQ = () => {
  return (
    <main>
    <Faqtopbox title="New User" subtitle="FAQs" para="Welcome to our Frequently Asked Questions (FAQ)
page! If you're new to our Local Tasker website, you
might have a lot of questions. This page is designed
to help you better understand our platform, how it
works, and how to get the most out of our services." img1="/FAQ.png" img2="/FAQbigcircle.png" img="/FAQbigcircle.png"/>
<Faqbox/>
<div className='desktopboxdisplay'><Subcribe/></div>
   <MobileSubcribe/>
    </main>
  )
}

export default FAQ