import React from 'react'
import QuestionAnswer from '../Howitworks/QuestionAnswer'
import { CardLeft } from './CardLeft';
import { Becometopbox } from './becometopbox';
import { Becomeownboss } from './Becomeownboss';
import { Becomeownboss1 } from './Becomeownboss1';
import { MobileSubcribe } from '../Component/share/mobileSubcribe';
import { MobileCardLeft } from './mobileCardLeft';

export const metadata = {
  title: 'Become a tasker',
  description: 'Generated by create next app',
}

const Becometasker = () => {
  return (
    <>
    <Becometopbox title="Flexible Work " subtitle="Opportunities That
Are" para="Find local jobs that fit your skills and schedule! Be
your own boss and enjoy the freedom that comes
with it! Get the support you need from Local
Tasker whenever you need it." img1="/sliderbigcircle.png" img2="/smallcircle.png" img3="/smallcircle(2).png"/>
    <Becomeownboss/>
    <Becomeownboss1/>
    <div className='desktopboxdisplay howmobileitworkmargintop'>
    <CardLeft title="Make Money Your Way" para1 ="For just £19.99 a month, you can become a Local Tasker
and start growing your business. And for a limited time,
we're offering a special promotion: sign up now and get
your first month for free! We believe in providing
affordable and accessible opportunities for people to
start their own businesses." btnvalue="Get Started" img="/makemoneyyourway.png" link='https://app.localtasker.co.uk/tasker-registration?type=1'/>
</div>
    <MobileCardLeft/>
    <QuestionAnswer btnvalue="/EtiquetteGuide"/>
     <MobileSubcribe />
    </>
  )
}

export default Becometasker