import React from 'react'
import { OurStory } from '../Component/share/OurStory';
import { CardLeft } from '../become_a_tasker/CardLeft';
import CardRight from './CardRight';
import CenterCard from './CenterCard';
import { MobileSubcribe } from '../Component/share/mobileSubcribe';
import { MobileOurstory } from '../Component/share/mobileOurstory';
import { MobileCardLeft } from '../Component/share/MobileCardLeft';

export const metadata = {
  title: 'Press Room',
  description: 'Generated by create next app',
}

const Pressroom = () => {
  return (
    <main>
    <div className='desktopboxdisplay'>
    <OurStory title="Local Tasker" subtitle="Press Room" para="Welcome to the Local Tasker Press Room! This is
where you'll find our latest news, press releases,
and resources related to our work and mission. " btnvalue="Browse Press Kit" img1="/circle1room.png" img2="/bigcircleroom.png" link='/Contact_us'/>
    </div>
      <div className='mobiledisplay'>
      <MobileOurstory title="Local Tasker" subtitle="Press Room" para="Welcome to the Local Tasker Press Room! This is where you'll
find our latest news, press releases, and resources related to
our work and mission." btnvalue="Browse Press Kit" img="/assets/pressMobile.JPG" link='/'/>
    </div>
    <div id="pressleftcvmf">
    <CardLeft title="Stay Connected" para1="Stay up-to-date with the dynamic world of Local
Tasker as we bring you the latest news and media
coverage. Discover how our community of taskers is
revolutionising productivity and empowering
individuals to achieve more." para2="Whether you're a journalist, a blogger, or simply
curious about what we're doing, we're here to provide
the information you need." img="/stayconnected.png" btnvalue="Read Blog" link='/Blog'/>
    </div>
<MobileCardLeft title="Stay Connected" para1="Stay up-to-date with the dynamic world of Local
Tasker as we bring you the latest news and media
coverage. Discover how our community of taskers is
revolutionising productivity and empowering
individuals to achieve more." para2="Whether you're a journalist, a blogger, or simply
curious about what we're doing, we're here to provide
the information you need." img="/stayconnected.png" btnvalue="Read Blog"/>
<CardRight/>
<CenterCard/>
 <MobileSubcribe/>
    </main>
  )
}

export default Pressroom