import React from 'react'
import { ContactBox } from './ContactBox'
import { Subcribe } from '../Component/share/Subcribe';
import { MobileSubcribe } from '../Component/share/mobileSubcribe';

export const metadata = {
  title: 'Contact Us',
  description: 'Generated by create next app',
}

const Contact = () => {
  return (
    <main>
     <ContactBox/>
     <div className='desktopboxdisplay'><Subcribe/></div>
     <div className='container-fluid mobiledisplay' style={{backgroundColor:"#2c86f1",marginTop:"0rem"}}>
    <div className='container pt-1 pb-4'>
    <h1 className='subcribetitle'>Ready to get started</h1>
    <div className='subcribe-btn-container'>
    <button className='btn1'  onClick={()=>router.push('https://app.localtasker.co.uk/register?type=2')}>Hire a Tasker</button>
    <button className='btn2'  onClick={()=>router.push('https://app.localtasker.co.uk/register?type=1')}>Become a Tasker</button></div>
    <div className='subcribe-container-subinputbox mt-4'>
    <input placeholder='Enter your email'/>
    <button>Register Now</button>
    </div>
     <p className='subcribeinputpara'>Sign-up for the latest news and updates!</p>
    </div>
    </div>
    </main>
  )
}

export default Contact