import React from 'react'
import { OurStory } from '../Component/share/OurStory'
import { Subcribe } from '../Component/share/Subcribe';
import { Faqtopbox } from '../F&Q/faqtopbox';
import { Communitybox } from './communitybox';
import { MobileSubcribe } from '../Component/share/mobileSubcribe';

export const metadata = {
  title: 'Community Guidlines',
  description: 'Generated by create next app',
}

const Community = () => {
  return (
    <main>
    <Faqtopbox title="Community" subtitle="Guidelines" para="Welcome to our Community Guidelines page! If
you're a new user on our Local Tasker platform, we're
delighted to have you here. These guidelines are an
essential part of our commitment to building a
respectful, trustworthy, and professional community." img1="/Commguidleines.png" img2="/commguidelinebigcircle.png" img="/Commguidleines.png"/>   
      <Communitybox/>
      <div className='desktopboxdisplay'><Subcribe/></div>
   <MobileSubcribe/>
    </main>
  )
}

export default Community